#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Phase 4c mechanism analysis.

Runs mechanism-level analyses on full step logs generated by
phase4c_mechanism_full_log_runner.py.

Analyses
--------
1. Lag-order analysis:
   self-appraisal gap at t -> selected anonymous signal in t+1..t+3;
   selected signal at t -> receiver recovery in t..t+5.

2. Mediation analysis:
   self_appraisal_gap -> selected_channel_signal -> receiver_recovery,
   with controls for relief, safe_surprise, damage, actual_risk, prediction_error.
   Uses cluster bootstrap by episode.

3. Matched-event analysis:
   compares high vs low self-appraisal-gap rows within strata matched on
   event, risk_regime, actual-risk bin, damage bin, prediction-error bin,
   and viability bin.

4. Counterfactual appraisal-swap analysis:
   compares selected-channel probability under the actual stored past appraisal,
   no-past-appraisal, low-past-threat, high-past-threat, and no-relief variants.

No LAUGH/HUMOR label is introduced; all analyses use selected anonymous signals.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd

EPS = 1e-9


def clip01(x):
    return np.clip(x, 0.0, 1.0)


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -40, 40)))


def zscore_df(df: pd.DataFrame, cols: List[str]) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    X0 = df[cols].to_numpy(dtype=float)
    mu = X0.mean(axis=0)
    sd = X0.std(axis=0) + 1e-6
    return (X0 - mu) / sd, mu, sd


def ridge_logistic(df: pd.DataFrame, y_col: str, x_cols: List[str], max_iter: int = 450) -> Dict[str, float]:
    sub = df[[y_col] + x_cols].replace([np.inf, -np.inf], np.nan).dropna()
    if len(sub) < 30 or sub[y_col].sum() < 3 or sub[y_col].sum() > len(sub) - 3:
        return {"n": len(sub), "events": float(sub[y_col].sum()) if len(sub) else 0.0, "intercept": 0.0, "pseudo_r2": 0.0, **{f"coef_{c}": 0.0 for c in x_cols}}
    Xs, _, _ = zscore_df(sub, x_cols)
    X = np.column_stack([np.ones(len(Xs)), Xs])
    y = sub[y_col].to_numpy(dtype=float)
    beta = np.zeros(X.shape[1])
    pos_w = 0.5 / max(y.mean(), 1e-4)
    neg_w = 0.5 / max(1 - y.mean(), 1e-4)
    wts = np.where(y > 0.5, pos_w, neg_w)
    lam = 0.06
    lr = 0.045
    for _ in range(max_iter):
        p = sigmoid(X @ beta)
        grad = (X.T @ ((p - y) * wts)) / len(y)
        grad[1:] += lam * beta[1:]
        beta -= lr * grad
    p = np.clip(sigmoid(X @ beta), 1e-6, 1 - 1e-6)
    null = np.clip(np.repeat(y.mean(), len(y)), 1e-6, 1 - 1e-6)
    ll = float(np.sum(y * np.log(p) + (1-y) * np.log(1-p)))
    ll0 = float(np.sum(y * np.log(null) + (1-y) * np.log(1-null)))
    pseudo = 1 - ll/ll0 if abs(ll0) > EPS else 0.0
    out = {"n": len(sub), "events": float(y.sum()), "intercept": float(beta[0]), "pseudo_r2": float(pseudo)}
    for c, b in zip(x_cols, beta[1:]):
        out[f"coef_{c}"] = float(b)
    return out


def ridge_ols(df: pd.DataFrame, y_col: str, x_cols: List[str], lam: float = 1e-4) -> Dict[str, float]:
    sub = df[[y_col] + x_cols].replace([np.inf, -np.inf], np.nan).dropna()
    if len(sub) < 20:
        return {"n": len(sub), "intercept": 0.0, "r2": 0.0, **{f"coef_{c}": 0.0 for c in x_cols}}
    Xs, _, _ = zscore_df(sub, x_cols)
    y = sub[y_col].to_numpy(dtype=float)
    y_mu = y.mean()
    y_sd = y.std() + 1e-6
    yz = (y - y_mu) / y_sd
    X = np.column_stack([np.ones(len(Xs)), Xs])
    I = np.eye(X.shape[1]); I[0, 0] = 0.0
    beta = np.linalg.pinv(X.T @ X + lam * I) @ X.T @ yz
    pred = X @ beta
    ss_res = float(np.sum((yz - pred) ** 2))
    ss_tot = float(np.sum((yz - yz.mean()) ** 2))
    r2 = 1 - ss_res / ss_tot if ss_tot > EPS else 0.0
    out = {"n": len(sub), "intercept": float(beta[0]), "r2": float(r2)}
    for c, b in zip(x_cols, beta[1:]):
        out[f"coef_{c}"] = float(b)
    return out


def add_future_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.sort_values(["episode_id", "t"]).copy()
    parts = []
    for _, g in df.groupby("episode_id", sort=False):
        g = g.copy().sort_values("t")
        # future selected signal within short window after current appraisal.
        fut_sig = np.zeros(len(g))
        sig = g["selected_channel_signal"].to_numpy(dtype=float)
        rec = g["receiver_recovery"].to_numpy(dtype=float)
        fut_rec = np.zeros(len(g))
        for lag in (1, 2, 3):
            fut_sig[:-lag] = np.maximum(fut_sig[:-lag], sig[lag:])
        # post-signal receiver recovery window. Include current row because listener
        # effect is applied at emission time; include following rows to test spread.
        for lag in range(0, 6):
            if lag == 0:
                fut_rec = np.maximum(fut_rec, rec)
            else:
                fut_rec[:-lag] = np.maximum(fut_rec[:-lag], rec[lag:])
        g["future_signal_1_3"] = fut_sig
        g["future_receiver_recovery_0_5"] = fut_rec
        parts.append(g)
    return pd.concat(parts, ignore_index=True) if parts else df


def lag_analysis(df: pd.DataFrame, outdir: Path) -> pd.DataFrame:
    rows = []
    controls = ["relief", "safe_surprise", "self_appraisal_gap", "damage", "actual_risk", "prediction_error"]
    for cond in sorted(df["condition"].unique()):
        sub = df[df["condition"] == cond].copy()
        fit_signal = ridge_logistic(sub, "future_signal_1_3", controls)
        fit_signal.update({"condition": cond, "target": "future_signal_1_3", "model": "gap_to_future_signal"})
        rows.append(fit_signal)
        rec_df = sub.copy()
        # signal precedes recovery: does signal_t predict receiver recovery window after controls?
        rec_controls = ["selected_channel_signal", "relief", "safe_surprise", "self_appraisal_gap", "damage", "actual_risk", "prediction_error"]
        fit_rec = ridge_ols(rec_df, "future_receiver_recovery_0_5", rec_controls)
        fit_rec.update({"condition": cond, "target": "future_receiver_recovery_0_5", "model": "signal_to_future_receiver_recovery"})
        rows.append(fit_rec)
    res = pd.DataFrame(rows)
    res.to_csv(outdir / "lag_mechanism_summary.csv", index=False)
    return res


def mediation_point(df: pd.DataFrame) -> Dict[str, float]:
    controls = ["relief", "safe_surprise", "damage", "actual_risk", "prediction_error"]
    # a path: X -> M, logistic coefficient for self_appraisal_gap.
    a_fit = ridge_logistic(df, "selected_channel_signal", ["self_appraisal_gap"] + controls)
    a = a_fit.get("coef_self_appraisal_gap", 0.0)
    # b and c' paths: M + X -> Y.
    y_fit = ridge_ols(df, "receiver_recovery", ["selected_channel_signal", "self_appraisal_gap"] + controls)
    b = y_fit.get("coef_selected_channel_signal", 0.0)
    c_prime = y_fit.get("coef_self_appraisal_gap", 0.0)
    # total effect c: X -> Y.
    c_fit = ridge_ols(df, "receiver_recovery", ["self_appraisal_gap"] + controls)
    c_total = c_fit.get("coef_self_appraisal_gap", 0.0)
    return {
        "a_gap_to_signal": float(a),
        "b_signal_to_receiver": float(b),
        "indirect_ab": float(a * b),
        "c_prime_gap_to_receiver_controlled_signal": float(c_prime),
        "c_total_gap_to_receiver": float(c_total),
        "n": int(len(df)),
        "events": float(df["selected_channel_signal"].sum()),
    }


def cluster_bootstrap(df: pd.DataFrame, fn, n_boot: int, seed: int = 123) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    eps = df["episode_id"].dropna().unique()
    rows = []
    if len(eps) < 2:
        return pd.DataFrame(rows)
    groups = {e: g for e, g in df.groupby("episode_id")}
    for b in range(n_boot):
        pick = rng.choice(eps, size=len(eps), replace=True)
        boot = pd.concat([groups[e] for e in pick], ignore_index=True)
        out = fn(boot)
        out["bootstrap"] = b
        rows.append(out)
    return pd.DataFrame(rows)


def mediation_analysis(df: pd.DataFrame, outdir: Path, n_boot: int) -> Tuple[pd.DataFrame, pd.DataFrame]:
    rows = []
    boot_rows = []
    for cond in sorted(df["condition"].unique()):
        sub = df[df["condition"] == cond].copy()
        point = mediation_point(sub)
        point["condition"] = cond
        rows.append(point)
        if n_boot > 0 and cond in ("full", "no_self_appraisal", "random_signal", "label_rule_signal"):
            boot = cluster_bootstrap(sub, mediation_point, n_boot=n_boot, seed=2026)
            if not boot.empty:
                boot["condition"] = cond
                boot_rows.append(boot)
    point_df = pd.DataFrame(rows)
    point_df.to_csv(outdir / "mediation_summary.csv", index=False)
    if boot_rows:
        boot_df = pd.concat(boot_rows, ignore_index=True)
        cis = []
        for cond, g in boot_df.groupby("condition"):
            row = {"condition": cond}
            for col in ["a_gap_to_signal", "b_signal_to_receiver", "indirect_ab", "c_prime_gap_to_receiver_controlled_signal", "c_total_gap_to_receiver"]:
                row[f"{col}_ci_low"] = float(np.quantile(g[col], 0.025))
                row[f"{col}_ci_high"] = float(np.quantile(g[col], 0.975))
                row[f"{col}_boot_mean"] = float(g[col].mean())
            cis.append(row)
        ci_df = pd.DataFrame(cis)
        boot_df.to_csv(outdir / "mediation_bootstrap_samples.csv", index=False)
        ci_df.to_csv(outdir / "mediation_bootstrap_ci.csv", index=False)
    else:
        boot_df = pd.DataFrame()
    return point_df, boot_df


def add_bins(df: pd.DataFrame, col: str, q: int, prefix: str) -> pd.Series:
    try:
        return pd.qcut(df[col].rank(method="first"), q=q, labels=False, duplicates="drop").astype(int)
    except Exception:
        return pd.Series(np.zeros(len(df), dtype=int), index=df.index)


def matched_event_analysis(df: pd.DataFrame, outdir: Path) -> pd.DataFrame:
    rows = []
    for cond in sorted(df["condition"].unique()):
        sub = df[df["condition"] == cond].copy()
        if len(sub) < 100:
            continue
        sub["risk_bin"] = add_bins(sub, "actual_risk", 5, "risk")
        sub["damage_bin"] = add_bins(sub, "damage", 4, "damage")
        sub["pe_bin"] = add_bins(sub, "prediction_error", 5, "pe")
        sub["viability"] = np.minimum(sub["integrity"], sub["energy"])
        sub["viability_bin"] = add_bins(sub, "viability", 4, "viab")
        # Use within-condition median, then compare only inside matched strata.
        med = sub["self_appraisal_gap"].median()
        sub["gap_high"] = (sub["self_appraisal_gap"] > med).astype(int)
        strata_cols = ["event", "risk_regime", "risk_bin", "damage_bin", "pe_bin", "viability_bin"]
        diffs = []
        for key, g in sub.groupby(strata_cols, dropna=False):
            if g["gap_high"].nunique() < 2:
                continue
            lo = g[g["gap_high"] == 0]
            hi = g[g["gap_high"] == 1]
            if len(lo) < 2 or len(hi) < 2:
                continue
            w = min(len(lo), len(hi))
            diffs.append({
                "weight": w,
                "signal_diff_high_minus_low": float(hi["selected_channel_signal"].mean() - lo["selected_channel_signal"].mean()),
                "receiver_diff_high_minus_low": float(hi["receiver_recovery"].mean() - lo["receiver_recovery"].mean()),
                "own_recovery_diff_high_minus_low": float(hi["own_recovery"].mean() - lo["own_recovery"].mean()),
                "n_hi": len(hi), "n_low": len(lo),
            })
        if diffs:
            ddf = pd.DataFrame(diffs)
            w = ddf["weight"].to_numpy(dtype=float)
            row = {
                "condition": cond,
                "n_strata": len(ddf),
                "matched_weight": float(w.sum()),
                "signal_diff_high_minus_low": float(np.average(ddf["signal_diff_high_minus_low"], weights=w)),
                "receiver_diff_high_minus_low": float(np.average(ddf["receiver_diff_high_minus_low"], weights=w)),
                "own_recovery_diff_high_minus_low": float(np.average(ddf["own_recovery_diff_high_minus_low"], weights=w)),
            }
        else:
            row = {"condition": cond, "n_strata": 0, "matched_weight": 0.0, "signal_diff_high_minus_low": 0.0, "receiver_diff_high_minus_low": 0.0, "own_recovery_diff_high_minus_low": 0.0}
        rows.append(row)
    res = pd.DataFrame(rows)
    res.to_csv(outdir / "matched_event_analysis.csv", index=False)
    return res


def counterfactual_swap_analysis(df: pd.DataFrame, outdir: Path) -> pd.DataFrame:
    rows = []
    needed = ["actual_prob_selected", "cf_no_past_prob_selected", "cf_low_past_prob_selected", "cf_high_past_prob_selected", "cf_no_relief_prob_selected"]
    for cond in sorted(df["condition"].unique()):
        sub = df[(df["condition"] == cond) & (df["selected_channel"] >= 0)].copy()
        if sub.empty or any(c not in sub.columns for c in needed):
            rows.append({"condition": cond, "n": len(sub)})
            continue
        row = {"condition": cond, "n": int(len(sub))}
        for col in needed:
            row[f"{col}_mean"] = float(sub[col].mean())
        row["actual_minus_no_past"] = float((sub["actual_prob_selected"] - sub["cf_no_past_prob_selected"]).mean())
        row["high_minus_low_past"] = float((sub["cf_high_past_prob_selected"] - sub["cf_low_past_prob_selected"]).mean())
        row["actual_minus_no_relief"] = float((sub["actual_prob_selected"] - sub["cf_no_relief_prob_selected"]).mean())
        # focus specifically on currently safe/high past-threat cases.
        focus = sub[(sub["current_safety"] >= 0.60) & (sub["past_threat"] >= 0.34)]
        row["focus_n"] = int(len(focus))
        if len(focus):
            row["focus_actual_minus_no_past"] = float((focus["actual_prob_selected"] - focus["cf_no_past_prob_selected"]).mean())
            row["focus_high_minus_low_past"] = float((focus["cf_high_past_prob_selected"] - focus["cf_low_past_prob_selected"]).mean())
        else:
            row["focus_actual_minus_no_past"] = 0.0
            row["focus_high_minus_low_past"] = 0.0
        rows.append(row)
    res = pd.DataFrame(rows)
    res.to_csv(outdir / "counterfactual_swap_summary.csv", index=False)
    return res


def write_report(outdir: Path, lag_df: pd.DataFrame, med_df: pd.DataFrame, match_df: pd.DataFrame, cf_df: pd.DataFrame, df: pd.DataFrame):
    full_lag = lag_df[lag_df["condition"] == "full"]
    full_med = med_df[med_df["condition"] == "full"]
    full_match = match_df[match_df["condition"] == "full"]
    full_cf = cf_df[cf_df["condition"] == "full"]
    lines = []
    lines.append("Phase 4c mechanism analysis report")
    lines.append("===================================")
    lines.append("")
    lines.append(f"Rows analysed: {len(df)}")
    lines.append(f"Conditions: {', '.join(sorted(df['condition'].unique()))}")
    lines.append("")
    lines.append("Full-model key mechanism outputs:")
    if not full_lag.empty:
        for _, r in full_lag.iterrows():
            lines.append(f"- lag {r['model']} target={r['target']}: coef_self_appraisal_gap={r.get('coef_self_appraisal_gap', np.nan):.6f}, coef_selected_channel_signal={r.get('coef_selected_channel_signal', np.nan):.6f}, pseudo/r2={r.get('pseudo_r2', r.get('r2', 0.0)):.6f}")
    if not full_med.empty:
        r = full_med.iloc[0]
        lines.append(f"- mediation a_gap_to_signal={r['a_gap_to_signal']:.6f}")
        lines.append(f"- mediation b_signal_to_receiver={r['b_signal_to_receiver']:.6f}")
        lines.append(f"- mediation indirect_ab={r['indirect_ab']:.6f}")
        lines.append(f"- mediation c_prime_gap_to_receiver_controlled_signal={r['c_prime_gap_to_receiver_controlled_signal']:.6f}")
    if not full_match.empty:
        r = full_match.iloc[0]
        lines.append(f"- matched strata={int(r['n_strata'])}, signal_diff_high_minus_low={r['signal_diff_high_minus_low']:.6f}, receiver_diff_high_minus_low={r['receiver_diff_high_minus_low']:.6f}")
    if not full_cf.empty:
        r = full_cf.iloc[0]
        lines.append(f"- counterfactual actual_minus_no_past={r.get('actual_minus_no_past',0):.6f}")
        lines.append(f"- counterfactual high_minus_low_past={r.get('high_minus_low_past',0):.6f}")
        lines.append(f"- counterfactual focus_high_minus_low_past={r.get('focus_high_minus_low_past',0):.6f}")
    lines.append("")
    lines.append("Interpretation rule:")
    lines.append("The self-appraisal-gap mechanism is strengthened only if: lag coefficient for self_appraisal_gap is positive, mediation indirect_ab is positive, matched high-gap rows emit more selected signal than matched low-gap rows, and counterfactual high-past appraisal increases selected-channel probability relative to low/no-past appraisal. These analyses still do not demonstrate subjective amusement.")
    lines.append("")
    lines.append("Generated files:")
    lines.append("- lag_mechanism_summary.csv")
    lines.append("- mediation_summary.csv")
    lines.append("- mediation_bootstrap_ci.csv, if bootstrap enabled")
    lines.append("- matched_event_analysis.csv")
    lines.append("- counterfactual_swap_summary.csv")
    (outdir / "mechanism_analysis_report.txt").write_text("\n".join(lines), encoding="utf-8")


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--step-log", required=True, help="Path to step_logs_mechanism.csv or .csv.gz")
    ap.add_argument("--outdir", default=None)
    ap.add_argument("--conditions", default="", help="Optional comma-separated condition subset")
    ap.add_argument("--bootstrap", type=int, default=300)
    ap.add_argument("--max-rows", type=int, default=0, help="Optional row cap for quick debugging")
    return ap.parse_args()


def main():
    args = parse_args()
    step_path = Path(args.step_log).expanduser()
    outdir = Path(args.outdir or (step_path.parent / "mechanism_analysis")).expanduser()
    outdir.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(step_path)
    if args.max_rows and len(df) > args.max_rows:
        df = df.sample(args.max_rows, random_state=1).sort_values(["episode_id", "t"])
    if args.conditions.strip():
        keep = [x.strip() for x in args.conditions.split(",") if x.strip()]
        df = df[df["condition"].isin(keep)].copy()
    required = ["episode_id", "t", "selected_channel_signal", "self_appraisal_gap", "relief", "safe_surprise", "damage", "actual_risk", "prediction_error", "receiver_recovery"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"step log is missing required columns: {missing}")
    df = add_future_columns(df)
    lag_df = lag_analysis(df, outdir)
    med_df, _ = mediation_analysis(df, outdir, n_boot=args.bootstrap)
    match_df = matched_event_analysis(df, outdir)
    cf_df = counterfactual_swap_analysis(df, outdir)
    write_report(outdir, lag_df, med_df, match_df, cf_df, df)
    print(f"[done] mechanism outputs written to {outdir}")


if __name__ == "__main__":
    main()
